version: '3.9'
services:
  web:
    build: .
    command: npm run dev:host
    ports:
      - "3000:3000"
    environment:
      - HOST=0.0.0.0
      - PORT=3000
    volumes:
      - .:/app
      - /app/node_modules
    working_dir: /app
